### PR TITLE
Polish styling of Q&A for topics

### PR DESCRIPTION
**Pull request by jankrcal**
This PR adds a bit of polish & visual unity to Q&A sections on the pages of topics:
 - trims down borders
 - turns black into light-gray
 - animates the chevron (via css)

### CODE REVIEW

**Comment by jankrcal** [comment]
@mgrabovsky: non-urgent

This is a minimal change so that I don't create a corresponding PR in web-cz, I'll roll the submodule in one PR.

**Comment by jankrcal** [comment]
@mgrabovsky: friendly ping!
(I know you were busy, this is still non-urgent)

**Comment by mgrabovsky** [comment]
I will take a look later today.

**Comment by jankrcal** [comment]
Thanks a million!

**Pull request merged**
