### PR TITLE
[Vyhledávání] Jednoduché javascriptové vyhledávání

### PR DESCRIPTION
**Pull request by jankrcal**
(Cherry-pick of a PR https://github.com/faktaoklimatu/web-cz/pull/752 from web-cz. Check it out for the previous discussion -- in Czech.)

Next steps:
 - Remake the search results into a list (with smaller thumbnails, title of the page as a normal text, ideally also with a snippet of the page that matches the search keywords). Maybe sort the results by content type to make sure we don't mix results with and without thumbnails.
 - (Maybe) Move the searchbox into the main toolbar a make the results box open from the searchbox as for search hints.

I feel the ownership for this effort but I am absolutely open to anyone else trying out stuff here and making progress.

### CODE REVIEW

**Comment by mukrop** [comment]
I see review request – is there anything new? I understood it was just a migration from the web-cz repository...

**Comment by mgrabovsky** [comment]
Briefly regarding UI:
- For the search results, I prefer some kind of dropdown over modal over a distinct page. Ideally, we would have one of the former two plus a page that would accept query parameters (something like `/search?q=paris`) for better accessibility, SEO and JavaScript-less browsing. Unfortunately, I don't think that's entirely possible with our current technology.
- I like having the search field right in the navbar, inviting the visitor to try it out if the need arises, something like the following (just a super-quick mockup):
  Screenshot_2021-01-31 Fakta o klimatu

**Comment by jankrcal** [comment]
I am sorry about the noise. This was just a migration, no new code. You were added as reviewers automatically when creating a PR (and I did not pay enough attention).

@mgrabovsky, thanks for the comments! I think we can easily implement /search?q=paris but it won't be javascript-less. Not sure if it's worth it, then.

And I think we're in agreement about the search results, I'll try to get some dropdown working (not very soon, though).

**Comment by jankrcal** [comment]
A just pushed a new version, please take a look!

Main changes:
- it's now more search-like with a small image and title and highlighted search snippets (highlighting of matches does not work in the title, yet) 
- it's implemented as a dropdown incl. key navigation in the results

**Comment by mukrop** [comment]
Very nice improvements, indeed!
* I'm still a bit concerned, how much text is indexed. Ideally, I'd like the whole accompanying texts – is that not viable with the current system? How large would the index file be?
* I've rather satisfied by the search results and agree with ranking infographics above other results.
* Small visuals: The found item's title, date and excerpt seem too similar in style to me. Maybe bolded (or larger?) title? Maybe brighter gray (or italics or prefix "publikovano: ") for the date?
* If nothing was found, I'd prefer a modal saying so (no there is no display).
* Mobile view does not work now (but you probably know that and it's just a prototype).
* Thinking of the mobile, there I'd expect the results on full-width. This brings me to thoughts if full width would not be better for the desktop version as well...
* Pressing Esc works to close the search box, but clicking in the area of the web does not (by intuition, I expected that). Would be different if the search field was full width though...
* Align the search box to the right in the navbar, not the center :-). Can we be as fancy as having a button with the magnifying glass (and maybe a small search box next to it) and when you click into it and start typing, it enlarges over the logo on the left? (googling around something between [this](https://codepen.io/milanraring/pen/qBdVwOP), [this](https://codepen.io/omarsherifs/pen/KGLYYW), [this](https://codepen.io/menelaosly/pen/rZddyb) and [this](https://codepen.io/CBeghin/pen/HeuiF).

**Comment by jankrcal** [comment]
Hey, another iteration to review. Addressed most of the comments. I'm quite happy with this UI both on desktop and on mobile. Please take a look.

What remains is:
 - saying "nothing found" (and maybe even saying "searching...")
 - index size: I've increased it from 300 to 3000. The full index was too slow to search in my testing. I'd like to get input on speed from your devices.

Beware, I've moved the dev-warning to bottom-right, much smaller now. It was driving me crazy (I've been bitten by the larger size of the navbar in dev so many times that I actually feel quite strongly about doing this change).

Please don't comment (much) on the technical code, yet. It needs quite some polishing.

**Comment by jankrcal** [comment]
I've addressed all pending comments and polished the code, please take a look!

I am still curious about perceived performance of search with this size of index.

**Review by mukrop — CHANGES_REQUESTED** [review]
A great piece of work indeed! I corrected a few last bits and several comments are below.
* Visual: On mobile, the preview images could be slightly larger (or the type text slightly smaller). Currently, the type "Explainer" has the terminating "-r" wrapped on the second line.
* Visual: Do we not want to have the white strip with type also on infographics? (It would be clear and a bit more consistent.)
* Functionality: Currently, the main JS file always outputs the information of development build to the log. (This is a bug in production.) Can you maybe look into it? (By the way, the new dev warning is very nice!) To ease you testing, you can serve the production version locally with `JEKYLL_ENV=production bundle exec jekyll serve --trace`.
* Functionality: I'd be very interested in what people searched for. There are multiple ways to track this. It would be simple, if there was an URL argument (there's a simple switch for that in GA). Otherwise, we could generate and send a custom event (much more complicated now). Is there not a simple way to, e.g. add the query parameter to the site you visited after clicking in the search results? (this would only track successful final searches, but still valuable). Another option is to leave it be for now and add this after revising GA (we'd need to do it anyway in the upcoming months).

**Comment by mukrop** [comment]
One more bit: I'd be interested to get a short explanation how it actually works :-). Can we manage during the weekend?

**Comment by jankrcal** [comment]
> A great piece of work indeed! I corrected a few last bits and several comments are below.
> 
> * Visual: On mobile, the preview images could be slightly larger (or the type text slightly smaller). Currently, the type "Explainer" has the terminating "-r" wrapped on the second line.
Thanks, that's a good idea! I increased the previews (both on mobile and on desktop!) and decreased font sizes a bit.

> * Visual: Do we not want to have the white strip with type also on infographics? (It would be clear and a bit more consistent.)
I get the beauty of consistency but I'd hate to put the white stripe on infographics. It feels like too much noise to me, it's too heavy. Maybe if we start to have more and more non-infographics content, we may need to reconsider but now is still infographics the default type.

> * Functionality: Currently, the main JS file always outputs the information of development build to the log. (This is a bug in production.) Can you maybe look into it? (By the way, the new dev warning is very nice!) To ease you testing, you can serve the production version locally with `JEKYLL_ENV=production bundle exec jekyll serve --trace`.
Fixed.

> * Functionality: I'd be very interested in what people searched for. There are multiple ways to track this. It would be simple, if there was an URL argument (there's a simple switch for that in GA). Otherwise, we could generate and send a custom event (much more complicated now). Is there not a simple way to, e.g. add the query parameter to the site you visited after clicking in the search results? (this would only track successful final searches, but still valuable). Another option is to leave it be for now and add this after revising GA (we'd need to do it anyway in the upcoming months).

Done.

**Comment by jankrcal** [comment]
Thanks @mukrop! Please take another look.

@mgrabovsky if you want to take a look before putting it into production, please let us know. 
(to me, Martin's review is enough to guarantee a solid quality bar but I am more than happy to address any comments of yours)

**Comment by jankrcal** [comment]
> One more bit: I'd be interested to get a short explanation how it actually works :-). Can we manage during the weekend?

Sure, we can chat! What about in the morning work block?

**Review by mukrop — APPROVED** [review]
No more commets. Thanks!

**Comment by mgrabovsky** [comment]
Functionally, it seems to be working great (only tested it a bit), so I'm fine with shipping it.

**Pull request merged**
