### PR TITLE
Fix invalid html

### PR DESCRIPTION
**Pull request by ufonzak**
#16 

- `<a>` is invalid without `href` and role is `button` in this case.

### CODE REVIEW

**Review by mukrop — CHANGES_REQUESTED** [review]
Thanks for the pull requests. Are `a` tags invalid without `href` attribute in all occasions?
And, unfortunately, I totally don't understand the `role` attribute – I'd be grateful for either a good tutorial article or a simple explanation in a call. These will probably be wrong on multiple places.

Some further comments:
* You current proposed change breaks the tests (try `make check`) as `href="#"` is seen by _html-proofer_ as an invalid link. It seems OK to adjust the test setting (see [this thread](https://github.com/gjtorikian/html-proofer/issues/118)).
* This is probably a problem on all dropdowns. Please also check the layouts for infographic page (PNG download options, data dropdown) and dataset layout (data links). Searching the codebase for `dropdown` may also be useful.
* Local repositories are handled in local languages, `web-core` is kept in English (including PR and issues).

**Comment by ufonzak** [comment]
> Thanks for the pull requests. Are `a` tags invalid without `href` attribute in all occasions?
> And, unfortunately, I totally don't understand the `role` attribute – I'd be grateful for either a good tutorial article or a simple explanation in a call. These will probably be wrong on multiple places.
> 
> Some further comments:
> 
> * You current proposed change breaks the tests (try `make check`) as `href="#"` is seen by _html-proofer_ as an invalid link. It seems OK to adjust the test setting (see [this thread](https://github.com/gjtorikian/html-proofer/issues/118)).
> * This is probably a problem on all dropdowns. Please also check the layouts for infographic page (PNG download options, data dropdown) and dataset layout (data links). Searching the codebase for `dropdown` may also be useful.
> * Local repositories are handled in local languages, `web-core` is kept in English (including PR and issues).

Thank for the review. 

Yes, it seems like an anchor is invalid without `href`. The browser don't care but semantically it's invalid.

The role attribute is part of ARIA. Adding role="button" tells screenreader that clicking the element has action. Additionally aria-haspopup says it's menu.

From here: https://www.w3.org/TR/2016/WD-wai-aria-practices-1.1-20161214/examples/menu-button/menu-button-1/menu-button-1.html#:~:text=The%20aria%2Dhaspopup%20attribute%20defines,and%20close%20the%20popup%20menu.

```
The aria-haspopup attribute defines an element with role=button as a ARIA menu button design pattern and indicates the actions of the button are to open and close the popup menu.
```

Reading more on the topic, I think it should not be anchor at all. So I've changed it to div. That should also fix the link validator.

I went through the rest of the repos to find all anchors without `href` (using elaborate method of regex `<a ((?!href).)*>`). I've found one more.

**Review by mukrop — APPROVED** [review]
You broke the style a little bit – switching a to div resulted in non-matched CSS rule for navigation (I fixed that).

A similar dropdown situation is in `/_includes/infographic-dataset-sidebar.html`, though there it's set as `<button>`. Should we unify it or do you see the situation as different (and thus different usage as appropriate)?

**Comment by ufonzak** [comment]
> You broke the style a little bit – switching a to div resulted in non-matched CSS rule for navigation (I fixed that).
> 
> A similar dropdown situation is in `/_includes/infographic-dataset-sidebar.html`, though there it's set as `<button>`. Should we unify it or do you see the situation as different (and thus different usage as appropriate)?

Sorry about breaking the style. I totally have not noticed the text was upper case. I'll do more comparison to the deployed version next time. Thank you for fixing it.

I'll check the second navigation but I'd vote for unifying as long as they are similar enough.

**Comment by ufonzak** [comment]
I looked into making the buttons also html button rather than divs with button role as in `infographic-dataset-sidebar.html`. That dictates I should apply `btn` class otherwise I get nasty default browser buttons. In that case, I also get a glow and other stuff which come with .btn class
image

Please, let me know if you want to proceed with this. Otherwise, I'd consider them different enough to simply go ahead with what we have here.

**Comment by mukrop** [comment]
Hm, I'm hesitant. I don't mind the glow that much, but changing them to buttons means adjusting styles (current conditions require `a`) and setting margin and padding manually (buttons have them bigger by default and I don't want to increase the header size).

So all in all, I prefer keeping them as they are on the account of being a different use case. If you agree, you can merge the PR.

**Comment by mukrop** [comment]
Though this way it's still invalid as it's an `a` without `href` attribute. So maybe button in the end? (I'm split and would appreciate your opinion.)

**Comment by ufonzak** [comment]
> Though this way it's still invalid as it's an `a` without `href` attribute. So maybe button in the end? (I'm split and would appreciate your opinion.)

I am confused now. There are no more "a" without href around. At least not to my knowledge. In `/_includes/infographic-dataset-sidebar.html` there buttons.

**Comment by ufonzak** [comment]
Please merge if everything feels right to you, I am OK with that. 👍

**Comment by mukrop** [comment]
Ah, it's a `div` now, I checked a wrong version of the commit. Let's then keep the current state. Merging.

**Pull request merged**
