### PR TITLE
Fix #99.

### LINKED ISSUE #99: Add cm and K to list of units
Add centimeters (cm) and Kelvin (K) to the pattern in the space replacement plugin.

### PR DESCRIPTION
**Pull request by J08nY**

### CODE REVIEW

**Review by mukrop — APPROVED** [review]
Simple and nice, thanks.

I'll make this PR as a Hecktoberfest test. It should count in even without `hacktoberfest-accepted` label, since the repository has the correct topic set. If not, I'll try to ass the label.

**Comment by mukrop** [comment]
One more bit: Your commit message does not have the correct form to automatically close the issue after being merged. According to the [GitHub documentation](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue), you should have used either `Fix #99` or `Fix faktaoklimatu/web-core#99` (other verbs are also possible, see linked docs if interested).

I'll add the link manually to the PR.

**Comment by J08nY** [comment]
The issue link is weird, the commit has the correct formulation "Fix #99." see: https://patch-diff.githubusercontent.com/raw/faktaoklimatu/web-core/pull/115.patch

But thanks for the note and the merge.

**Comment by mukrop** [comment]
I see, you're right. Maybe the problem was caused by doing a PR from your fork, who knows.

**Pull request merged**
