### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by mgrabovsky**
- Update dependencies in the Bundler lockfile to their latest versions using `bundle update`.
- Update our usage of `html-proofer` for the latest version.

Follow-up to #214, #218 and #220.

### CODE REVIEW

**Comment by mgrabovsky** [comment]
@jankrcal I'm moving the discussion from #218 here.

I'm not completely happy with the `frozen` solution. If I understand the Bundler documentation correctly, it should only be used for deployment. However, I suppose we'll have to settle with it if there's no other way.

**Comment by mgrabovsky** [comment]
I'm reviving this since the [build now fails] due to outdated dependencies. Can you please check if this version of the lockfile works for you on Mac?

**Comment by mgrabovsky** [comment]
@jankrcal I'm reviving this since the [build now fails] due to outdated dependencies. Can you please check if this version of the lockfile works for you on Mac?

**Comment by jankrcal** [comment]
Not perfectly.

As before, it overwrites the Gemfile.lock:

```
diff --git a/Gemfile.lock b/Gemfile.lock
index 65c516c..cdae64f 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -25,7 +25,7 @@ GEM
     eventmachine (1.2.7)
     execjs (2.9.1)
     ffi (1.17.0)
-    ffi (1.17.0-x86_64-linux-gnu)
+    ffi (1.17.0-x86_64-linux)
     ffi-icu (0.5.3)
       ffi (~> 1.0, >= 1.0.9)
     fiber-annotation (0.2.0)
@@ -124,7 +124,7 @@ GEM
     sass-embedded (1.77.5)
       google-protobuf (>= 3.25, < 5.0)
       rake (>= 13)
-    sass-embedded (1.77.5-x86_64-linux-gnu)
+    sass-embedded (1.77.5-x86_64-linux)
       google-protobuf (>= 3.25, < 5.0)
     strscan (3.1.0)
     terminal-table (3.0.2)
```

I think a bit of hassle on Mac is better than a broken build. Any further ideas?

**Comment by mgrabovsky** [comment]
Hm, it looks like a lot of hassle to get this working on both. I suggest we merge this to unblock the builds and use the frozen/deployment config option if the lockfile bothers you.

**Comment by jankrcal** [comment]
Sounds good.

Dne so 15. 6. 2024 14:51 uživatel Matěj ***@***.***> napsal:

**Review by jankrcal — APPROVED** [review]

**Pull request merged**
