### PR TITLE
Tweak container deployment

### PR DESCRIPTION
**Pull request by mgrabovsky**
* Optimise Dockerfile to reduce intermediate layers.
* Update Dockerfile metadata.
* Mount volume with `:z` option to ensure correct SELinux labels.
* Change SELinux type mentioned in readme to a more general, safer one.
* Make WEBrick listen on `0.0.0.0` to avoid networking problems   on some systems.

### CODE REVIEW

**Review by mukrop — COMMENTED** [review]
I don't have any objections to the content changes, though running it on my Fedora successfully runs Jekyll, but not on `localhost:4000`. I usually don't use container build, but I think it worked previously. Any ideas?

PS: It may be convenient to add an explicit message after container build to adjust SELinux if necessary, I forgot about it again (or a message instructing you to read the ReadMe in case of running failures). What do you think?

**Comment by mgrabovsky** [comment]
I'm not sure I understand. When you run `make container`, the web server appears to be running but `localhost:4000` is not accessible?

**Comment by mukrop** [comment]
> I'm not sure I understand. When you run `make container`, the web server appears to be running but `localhost:4000` is not accessible?

Yes, exactly so. Works well with standard build, but not with a container build (in a separate folder, I know standard and container build don't cooperate well when run from the same directory).

**Comment by mgrabovsky** [comment]
Hm, strange. Is it from a fresh checkout and build (i.e. a new images was built by `make container` and a new container created)?

Could you verify that the following result is the same on your machine?

	$ podman inspect -f '{{.NetworkSettings.Ports}}' factsonclimate
	map[4000/tcp:[{ 4000}]]

Would adding `--port 4000` fix the issue?

**Comment by mukrop** [comment]
It was a fresh clone and container build. The mapping inspection is the same as you state.

As for adding `--port 4000`, where should I add it to? I tried adding it to `podman start -a factsonclimate` though that resulted in an unknown flag complaint.

**Comment by mgrabovsky** [comment]
> As for adding `--port 4000`, where should I add it to? I tried adding it to `podman start -a factsonclimate` though that resulted in an unknown flag complaint.

Sorry, I meant that as an argument to `jekyll serve`.

**Comment by mukrop** [comment]
No change :-/.

When you do a fresh clone & build & server, does it work OK? What OS?

**Comment by mgrabovsky** [comment]
OK, let's merge this. Thanks for the review.

**Pull request merged**
