### PR TITLE
#28 infographics resolution optimization

### PR DESCRIPTION
**Pull request by ufonzak**
Specifying the whole srcset so that browser can decide what resolution to load. I've changed the href to the highest resolution as I'd assume you want to best quality if you want to download it.

I've tested it in chrome with different resolutions. I could not quite get it to load 600, it would load always at least 1200. I think that's fine.

### CODE REVIEW

**Review by mgrabovsky — APPROVED** [review]
Looks good overall, though I suppose it could be further improved by using the [`sizes` attribute](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images#resolution_switching_different_sizes). It might perhaps solve the issue with Chrome not loading the smallest size (it works for me on Firefox). Are you going to give it a shot?

**Review by mukrop — CHANGES_REQUESTED** [review]
The solution seems to be different from [the one for explainer covers](https://github.com/faktaoklimatu/web-core/blob/3675a86c34f4c30adf4ccc57660deb83f1b238c2/_layouts/explainer.html#L35). If there is no reason to handle them differently, I'd prefer a consistent solution. Though I don't understand it much, so I can't say which is better. (In generally, I don't prefer inline `style`, but I cannot say more.)

**Comment by mukrop** [comment]
An just as a note, we already use `srcset` [in explainer figures](https://github.com/faktaoklimatu/web-core/blob/3675a86c34f4c30adf4ccc57660deb83f1b238c2/_includes/figure.html#L5).

**Comment by ufonzak** [comment]
> The solution seems to be different from [the one for explainer covers](https://github.com/faktaoklimatu/web-core/blob/3675a86c34f4c30adf4ccc57660deb83f1b238c2/_layouts/explainer.html#L35). If there is no reason to handle them differently, I'd prefer a consistent solution. Though I don't understand it much, so I can't say which is better. (In generally, I don't prefer inline `style`, but I cannot say more.)

According to what I've read on mozilla developer the srcset is the right way to handle the scaling of pictures. Picture tag or sizes is actually aimed that providing different pictures for mobile vs desktop, etc. The benefit of srcset is that the browser makes the choice. I think I am getting the bigger picture because I have a high DPI monitor. 

Perhaps, we should change the other usage. Unless we want to force the sizes does not seem to be the case.

**Comment by mgrabovsky** [comment]
> The solution seems to be different from [the one for explainer covers](https://github.com/faktaoklimatu/web-core/blob/3675a86c34f4c30adf4ccc57660deb83f1b238c2/_layouts/explainer.html#L35).

That is truly a suboptimal solution. Martin is right we should be using `srcset` whenever possible (which is everywhere for us so far).

> Picture tag or sizes is actually aimed that providing different pictures for mobile vs desktop, etc.

As far as I understand, both approaches are equivalent (at least in this basic scenario) and the browser chooses which size to download depending on disparate criteria. The decision depending on viewport size and depending on resolution are fundamentally the same thing.

`sizes` is used to provide hints to the browser as to how big the picture is going to be displayed inside the layout. (Though it's hard to tell what _complicated_ entails in general.)

I'm fine with either as long as it works as expected.

> I think I am getting the bigger picture because I have a high DPI monitor.

Yeah, that makes sense. I think I'd use the `2x`-type of syntax when thinking in terms of DPI, but I don't mind either way.

**Comment by ufonzak** [comment]
> The solution seems to be different from [the one for explainer covers](https://github.com/faktaoklimatu/web-core/blob/3675a86c34f4c30adf4ccc57660deb83f1b238c2/_layouts/explainer.html#L35). If there is no reason to handle them differently, I'd prefer a consistent solution. Though I don't understand it much, so I can't say which is better. (In generally, I don't prefer inline `style`, but I cannot say more.)

That's unfortunately different case. Here we use an image as the background of div. The only solution I am aware of is to use media queries (as we do). It's not easy to hack around not using background-image, I'd say it would lead to an even bigger mess. My general approach is unification as well but in this case, I don't see an easy way out. @mukrop

**Comment by ufonzak** [comment]
As far as inlining goes I wanted to persuade templates to at least generate the string from the number array but I have not found a satisfying solution.

**Review by mukrop — APPROVED** [review]
OK then, I agree the current proposed solution is probably the best.

Is there anything more, or can this be merged now?
(It seems mergeable, though I'm not sure.)

**Pull request merged**
