### PR TITLE
Minor search improvements

### LINKED ISSUE #43: Explainer licence button on mobile
The licence button in explainer cover images is barely clickable on mobile displays (only clicking the lower border works)

### PR DESCRIPTION
**Pull request by jankrcal**
Minor fix for raw html appearing in search snippets for some pages.

Fixes #43

### CODE REVIEW

**Comment by jankrcal** [comment]
Please hold off review, I'll fix one more issue with search.

**Comment by jankrcal** [comment]
Ready to review!

**Review by mukrop — CHANGES_REQUESTED** [review]
Hm, testoval si to? Ja ked to testujem v browsri, tak mi v mobilnom zobrazeni stale nejde kliknut na to tlacitko s licenciou... (ale pokazi sa to az od nejakej velkosti dole).

**Comment by jankrcal** [comment]
Testoval, funguje mi jak ve Firefoxu, tak Chrome.

Rozbije se to, až se když se se toolbar zalomí na dva řádky (to bych
neřešil).

J.

so 13. 3. 2021 v 21:10 odesílatel Martin Ukrop ***@***.***>
napsal:

**Comment by mukrop** [comment]
It seems working now, I must have built it in a wrong way. Apologies!

**Review by mukrop — APPROVED** [review]

**Pull request merged**
