### PR TITLE
Unify CDN links to cloudflare.com

### PR DESCRIPTION
**Pull request by jankrcal**
This decreases the attack surface to one single CDN.

### CODE REVIEW

**Comment by jankrcal** [comment]
After the discussion, I think what makes sense is to unify it all.
Requesting review from both of you, please take a look!

I haven't updated any of the versions, we should do it as well, sooner or later.

**Review by mgrabovsky — APPROVED** [review]
Wow, that's one step beyond what I was suggesting. Looks fine to me, good work.

**Review by mukrop — CHANGES_REQUESTED** [review]
Nice, thanks!
Can I ask you to do a corresponding PR in the web-cz repozitory that cleans the CSP settings?

**Review by mukrop — APPROVED** [review]
Nice, thanks.

**Pull request merged**
