### PR TITLE
Fix Gemfile (automatically updated on Mac)

### PR DESCRIPTION
**Pull request by jankrcal**
This is a change that happens on every build on my Mac.

### CODE REVIEW

**Comment by jankrcal** [comment]
@mgrabovsky Could you please check if this works for you (i.e. a local build of yours does not overwrite it again)? Sorry for not catching it on the previous PR.

**Comment by jankrcal** [comment]
Closed as I reverted the original PR (see https://github.com/faktaoklimatu/web-core/pull/220). @mgrabovsky Could you please reopen the original PR and make sure 'make check' works?

**Comment by mgrabovsky** [comment]
This change doesn't work for me:

    Could not find sass-embedded-1.58.3-x86_64-linux in any of the source

**Comment by jankrcal** [comment]
Good to know!

I've tested now that the `frozen` config seems to work for me: https://bundler.io/v1.12/man/bundle-config.1.html
(i.e., adding `BUNDLE_FROZEN: true` to `web-core/.bundle/config`)
Once we have a new PR relanding the changes in Gemfile.lock, can you test of this config works for you as well?

If not, I can always set it up locally in `~/.bundle/config` but that's suboptimal for other developers on Mac.

**Pull request closed without merging**
