### PR TITLE
Turn lists of preview boxes into expandable lists

### PR DESCRIPTION
**Pull request by jankrcal**
This CL implements a generic feature for the web: expandable lists of preview boxes. 
- By default, each list is collapsed and shows only a given number of boxes. The list can be expanded using a "More" button and collapsed again using a "Less" button.
- The lists are smart in the sense that (when collapsed) they display a different amount of boxes on each viewport: 6 on lg (desktop), 4 on md (tablet), 2 on sm (mobile). All that corresponds to 2 rows of content.

### CODE REVIEW

**Comment by jankrcal** [comment]
@katkolouchova Could you please take a look?

(Sorry @mgrabovsky for notifying you, that was a misclick. Obviously, fee free to take a look but no need to.)

**Review by katkolouchova — APPROVED** [review]
Looks good, I would only suggest increasing margin above the button (ideally use the same margin as in between the rows:
image

I've tested functionality and UX, I cannot do proper code review though.

**Comment by jankrcal** [comment]
Okay, I've enlarged the margins. Do I get it right you're fine with 2 rows of content on desktop?

**Comment by katkolouchova** [comment]
You do :)

**Pull request merged**
