### PR TITLE
Explainers - finishing improvements

### PR DESCRIPTION
**Pull request by jankrcal**
This PR improves the layout for explainers and makes sure they can get displayed from elsewhere in the web.

### CODE REVIEW

**Comment by jankrcal** [comment]
Martin, could you please take a technical look?
(Matěj, adding you as an optional reviewer)

**Review by mukrop — CHANGES_REQUESTED** [review]
Toto vyzera tiez dobre. Len prosim zvazit, ze ak treti explainer bude nepublikovany, tak idealne vyhadzat tie podmienky, ktore vylucuju objekty s nastavenym `sitemap: false`.

**Comment by jankrcal** [comment]
Thanks, comments addressed, please take another look!

(I am puzzled, are we using English or Czech in the core repo?)

**Comment by jankrcal** [comment]
@mukrop Friendly ping, please take another look!

**Comment by mukrop** [comment]
I'm sorry, but I'm rather busy this week :-/.
(Lecturing on Friday but noy being prepared yet.)
I may manage tomorrow/Friday, though I cannot guaranee that. If it does not
work, I'll manage over the weekend.

**Review by mukrop — APPROVED** [review]

**Pull request merged**
