### PR TITLE
Adding fancybox to figures and infographics

### LINKED ISSUE #76: Add lightbox to infographics and images
Infographics and explainer images are currently opened as a media file on click. A lightbox solution would be better.

### PR DESCRIPTION
**Pull request by ufonzak**
Resolves #76 

Adding fancybox. I decided to use version 3.7.2 (opposed to 4.alpha4) because of the download button and stability. The transition to version 4 would not be all that hard if we decide to do so later.
I've added the translation for SK and CS (please check).
I've introduced a new global object `fakta` where we can put information from our templating.
Please let me know if there is another place where the lightbox should go.

Thanks.

### CODE REVIEW

**Comment by mukrop** [comment]
We've gone through the update with @kikinna and have the following comments:
* Infographics and Explainer images work mostly OK, thanks! (Kristi was delighted, she is really looking forward to this functionality!)
* [ ] Let's not have the donwload button in the fancybox at all. There are multiple formats and sizes of each graphics (and soon, there will be even more). With the download more involved, we prefer to have the options in the website and not have just one in the fancybox.
* [ ] Does fancybox natively support image captions? Let's enable it for explainer images. (Though not for infographics, as the current caption is often long and would be rather impractical on mobile.)
* [ ] SVG images are problematic (see for example the [explainer on IPCC reports](https://faktaoklimatu.cz/explainery/zpravy-ipcc)). Can we make SVGs to scale to the screen automatically in fancybox? Or do you thing it would be necessary to display the automatically-created PNG version? As for the background, we can make a standard that SVG explainer images will have it or have it added automatically in PNG cconversion, should we choose that way.
* I don't mind which version of fancybox we use, but alpha version seems a bit too cutting edge for this project :-).

**Comment by ufonzak** [comment]
Thank you for testing the changes and your comments!

> We've gone through the update with @kikinna and have the following comments:
> 
> * Infographics and Explainer images work mostly OK, thanks! (Kristi was delighted, she is really looking forward to this functionality!)
> * [ ]  Let's not have the donwload button in the fancybox at all. There are multiple formats and sizes of each graphics (and soon, there will be even more). With the download more involved, we prefer to have the options in the website and not have just one in the fancybox.
Removed the button.
> * [ ]  Does fancybox natively support image captions? Let's enable it for explainer images. (Though not for infographics, as the current caption is often long and would be rather impractical on mobile.)
It does support it. I've added caption for explainers. It was not straightforward as the caption itself can contain HTML. So I had to use the `data-options`.
> * [ ]  SVG images are problematic (see for example the [explainer on IPCC reports](https://faktaoklimatu.cz/explainery/zpravy-ipcc)). Can we make SVGs to scale to the screen automatically in fancybox? Or do you thing it would be necessary to display the automatically-created PNG version? As for the background, we can make a standard that SVG explainer images will have it or have it added automatically in PNG cconversion, should we choose that way.
If we use `data-type="iframe"` it actually works quite nicely. Let me know if you are happy with the result. It's easy way out but I can do more if you find it lacking.
> * I don't mind which version of fancybox we use, but alpha version seems a bit too cutting edge for this project :-).

Looking forward to hearing more from you.

**Comment by mukrop** [comment]
Finally I'm a bit more free and can return to these things. Sorry for the great delay. I believe, we can finish this in the upcoming weeks.

* Overall, it functions very good! I've tested both desktop and mobile (portrait/landscape).
* [ ] As for the captions: Can you please update the code so that the same caption is displayed as on the page? That means including the automatically formatted author information. If links are problematic, let's just keep the text.
* As for the SVGs: I'm pleasantly surprised – it works better than I expected. The only trouble is that since fancybox does not allow custom zoom (or at least the scroll wheel does not do anything), you cannot zoom. On normal images, you can double-click to have the default resolution zoom (but SVGs don't have this option).
* [ ] Just a cross-check: IS custom zoom not a feature? If not, I'd actually be considering automatic PNG conversion of the  SVG images for easier viewing. What do you think? It may not be worth it (and it may be better to just publish as is and note the SVG zooming thing as an issue to be resolved later...)

**Comment by ufonzak** [comment]
> One more solution came to mind: Jekyll can process JS files as well (just add an empty header to them). That way, the localization strings can be saved along the other localization strings. Thus, fancybox does not need to know the language, removing the need for inlined JS getting the language. I find this probably even cleaner and more consistent solution than the existing one.

Done it this way. I hope I've included the JS file it right. Please let me know if it's all right.

 I've also added the translation string for czech version.  faktaoklimatu/web-cz#954

If you agree with this, can you please add slovak translation?

**Review by mukrop — APPROVED** [review]
Nice and thanks.

Good timing, by the way. Today I have a long day related to work for Fakta and planned to finish the implementation for you if necessary (since only this tiny detail remained).

I'll do also the Slovak translation, sure.

**Pull request merged**
