### PR TITLE
Update Ubuntu to 22.04

### PR DESCRIPTION
**Pull request by mgrabovsky**
Update the version of Ubuntu in Travis and Docker one notch (to 22.04) in order to fix build issues due to outdated Ruby version and related issues.

### CODE REVIEW

**Comment by mgrabovsky** [comment]
@jankrcal Could you please take a look at some point? The build in Travis stumbled on some more problems with old Ruby and I found the easiest solution to be just upgrading the distro.

The build is tested in faktaoklimatu/web-cz#1333.

**Comment by mgrabovsky** [comment]
@jankrcal I'm pushing this as it's blocking other work and I haven't discovered any problems with the changes so far. Feel free to review ex-post.

**Review by jankrcal — COMMENTED** [review]
Looks good to me.

Sounds legit to update from an 4 years old LTS to a 2 years old ;)
Have you considered updating to 24.04 or is it safer in terms of potential hassle to wait a bit for the distro to further stabilize?

**Comment by mgrabovsky** [comment]
I've tried 24.04 as well. I thought it had trouble installing Inkscape, but now I'm looking at the logs again and see that I had specified the distro incorrectly, so I might try upgrading 24.04 again some day.

**Pull request merged**
