### PR TITLE
Add Atom feed

### LINKED ISSUE #11: RSS/Atom feed
Automatically generate RSS/Atom feed for new content.

* Use https://github.com/jekyll/jekyll-feed
* Include all main content types (infographic, explainers). For now, do not include datasets (we'll drop them eventually) and pages (they have different sematics).
* Try to map as many fields as we have (title, author, description, preview image, ...).

### PR DESCRIPTION
**Pull request by mukrop**
Based on experience from #116, we build the Atom feed manually and not using the [jekyll-feed](https://github.com/jekyll/jekyll-feed) plugin. Nevertheless, we are building on [their template](https://github.com/jekyll/jekyll-feed/blob/master/lib/jekyll-feed/feed.xml).

Technicalities:
* Preview available here: https://cz-fakta-o-klimatu--preview-feed-5-f3tofcca.web.app
* We use Atom feed.
* We try to include full content, not just headlines.
  * Note: It is a bit tricky as we need to generated the stuff included by layout files manually and need to resolve Jekyll includes (glossary links may not be wanted but sidebars are!).

Resolves #11.

### CODE REVIEW

**Comment by mukrop** [comment]
To be done (see [feed definition](http://www.atomenabled.org/developers/syndication/)):
* [ ] Consider adding `logo` (1:2 ratio).
* [ ] Consider explicitly addind licence in `rights` (we use CC).
* [ ] Add `summary` for types that support it.
* [ ] Fix HTML display for content.
* [ ] Decide and resolve out custom tags (previewbox, glossary link).

**Comment by mukrop** [comment]
* [ ] Known issue: For some reason, cover images for explainers do not work in Feedly. Including them in the content tag as is the case of infographics may help.

**Review by mgrabovsky — APPROVED** [review]
Looks good to me.

I'm thinking it would be nice to have a validation step in the build, akin to the search JSON validation, just to be extra safe. It seems there's an [XML module](https://ruby-doc.org/stdlib-3.0.2/libdoc/rexml/rdoc/rexml-3_2_5/doc/rexml/context_rdoc.html) in the standard library, but I haven't checked for details.

**Comment by mukrop** [comment]
@mgrabovsky, I've added cover images also for explainers for more engaging preview (at least in Feedly) as well as XML validity testing. It was a bit difficult for me to use the module from the standard library, so I used XML capabilities of Nokogiri, since we use it anyway.

Can you briefly review it again (especially if the Ruby code is OK)?

**Review by mgrabovsky — APPROVED** [review]
Looks good to me.

**Pull request merged**
